# Generated by Django 4.1.1 on 2022-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=350)),
                ('contact', models.BigIntegerField()),
                ('message', models.CharField(max_length=400)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shivpquery',
            },
        ),
    ]
